apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-petclinic-lib
  description: Biblioteca Spring Petclinic Commons 
spec:
  type: library
  lifecycle: experimental
  owner: tanzu-brasil
  system: spring-petclinic
