apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: spring-sensors
  description: Spring Sensors Application
spec:
  owner: tanzu-brasil
  domain: tanzu
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-sensors
  description: Spring Sensors Spring Boot
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors'
spec:
  type: service
  lifecycle: alpha
  owner: tanzu-brasil
  system: spring-sensors