apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ddarocha
spec:
  profile:
    displayName: Diego Pereira da Rocha
    email: ddarocha@vmware.com
    picture: https://media.licdn.com/dms/image/C5603AQFaqATembpNTg/profile-displayphoto-shrink_400_400/0/1516577440592?e=1701907200&v=beta&t=XX6Twa8Um0kbt-wk6p31DwazrzRAJdzE7hpuWoK7ihw
  memberOf: [tanzu-brasil]